export const ACTION_TYPES = {
  //Counter
  INCREMENT_COUNT: 'INCREMENT_COUNT',
  DECREMENT_COUNT: 'DECREMENT_COUNT',
  SET_STEP: 'SET_STEP',
  //Tasks
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  ///Users CREATE
  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_REQUEST',
  CREATE_USER_ERROR: 'CREATE_USER_REQUEST'
};
